---
# handlers file for ansible-postgresql
- name: Reload PostgreSQL
  become: yes
  service:
    name=postgresql
    state=reloaded

- name: Restart PostgreSQL
  become: yes
  service:
    name=postgresql
    state=restarted
